package Corredores;

import java.awt.List;
import java.util.ArrayList;

public class InterfazCorredor extends javax.swing.JFrame {

    public InterfazCorredor() {
        initComponents();
        corredor1ProgressBar.setValue(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carreraJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        corredor1ProgressBar = new javax.swing.JProgressBar();
        corredor2ProgressBar = new javax.swing.JProgressBar();
        corredor2JLabel = new javax.swing.JLabel();
        corredor1Jlabel = new javax.swing.JLabel();
        simularCarreraJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("CARRERA DE HILOS");

        corredor2JLabel.setText("CORREDOR 2:");

        corredor1Jlabel.setText("CORREDOR 1:");

        simularCarreraJButton.setText("SIMULAR CARRERA");
        simularCarreraJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularCarreraJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout carreraJPanelLayout = new javax.swing.GroupLayout(carreraJPanel);
        carreraJPanel.setLayout(carreraJPanelLayout);
        carreraJPanelLayout.setHorizontalGroup(
            carreraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreraJPanelLayout.createSequentialGroup()
                .addGroup(carreraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corredor2ProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(carreraJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(carreraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corredor1ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(corredor2JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(carreraJPanelLayout.createSequentialGroup()
                                .addGroup(carreraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corredor1Jlabel)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                                .addComponent(simularCarreraJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        carreraJPanelLayout.setVerticalGroup(
            carreraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(carreraJPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(carreraJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simularCarreraJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corredor1Jlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corredor1ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(corredor2JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corredor2ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carreraJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carreraJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simularCarreraJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularCarreraJButtonActionPerformed

        Corredor[] corredores = new Corredor[2];
        Thread[] hilos = new Thread[corredores.length];

        for (int i = 0; i < corredores.length; i++) {
            corredores[i] = new Corredor("Corredor " + (i + 1));
            hilos[i] = new Thread(corredores[i]);
            hilos[i].start();
            corredor1ProgressBar.setValue(corredores[i].getMetrosRecorridos());
            corredor2ProgressBar.setValue(corredores[i].getMetrosRecorridos());
        }

        for (int i = 0; i < corredores.length; i++) {
            try {
                hilos[i].join();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                return;
            }
        }

        Corredor ganador = corredores[0];
        for (int i = 1; i < corredores.length; i++) {
            if (corredores[i].getMetrosRecorridos() > ganador.getMetrosRecorridos()) {
                ganador = corredores[i];
            }
        }
        
        
    }//GEN-LAST:event_simularCarreraJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel carreraJPanel;
    private javax.swing.JLabel corredor1Jlabel;
    private javax.swing.JProgressBar corredor1ProgressBar;
    private javax.swing.JLabel corredor2JLabel;
    private javax.swing.JProgressBar corredor2ProgressBar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton simularCarreraJButton;
    // End of variables declaration//GEN-END:variables
}
